# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-28 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.CharField(max_length=50, verbose_name='关键词')),
                ('contentType', models.CharField(max_length=20, verbose_name='类型')),
            ],
            options={
                'verbose_name_plural': '搜索',
                'verbose_name': '搜索',
            },
        ),
    ]
